disabled = false
languageCode = "pt-pt"
languageName = "Portuguese (Portugal)"
weight = 1
title = "Estio"

[params]
displayName = "PT"
isoCode = "pt"
rtl = false
dateFormat = "2 January 2006"
author = { name = "Hugo Santos (Ulmi)", image = "avatar.jpg", headline = "Engenheiro Florestal de profissão, mas mais um geospatial / data engineer", bio = "Engenheiro Florestal de profissão, mas mais um geospatial / data engineer", links = [ { email = "mailto:nuno@n9o.xyz" }, { linkedin = "https://linkedin.com/in/nunocoracao" }, { x-twitter = "https://twitter.com/ulmi" }, { github = "https://github.com/ulmi" }, { mastodon = "https://mastodon.social/@ulmi" }, { instagram = "https://instagram.com/nunocoracao" }, { goodreads = "http://goodreads.com/nunocoracao" } ] }
logo = "white_halo.png"
