disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Estio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
author = { name = "Hugo Santos (Ulmi)", image = "avatar.jpg", headline = "Forest engineer by trade, but really a geospatial / data engineer in the heart", bio = "Forest engineer by trade, but really a geospatial / data engineer in the heart", links = [ { email = "mailto:nuno@n9o.xyz" }, { linkedin = "https://linkedin.com/in/nunocoracao" }, { x-twitter = "https://twitter.com/ulmi" }, { github = "https://github.com/ulmi" }, { mastodon = "https://mastodon.social/@ulmi" }, { instagram = "https://instagram.com/nunocoracao" }, { goodreads = "http://goodreads.com/nunocoracao" } ] }
logo = "white_halo.png"
