disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Estio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
author = { name = "Hugo Santos (Ulmi)", image = "avatar.jpg", headline = "Engenheiro Florestal de profissão, mas mais um geospatial / data engineer", bio = "Engenheiro Florestal de profissão, mas mais um geospatial / data engineer", links = [ { linkedin = "https://linkedin.com/in/hdsantos" }, { x-twitter = "https://twitter.com/ulmi" }, { github = "https://github.com/ulmi" }, { mastodon = "https://mastodon.social/@ulmi" } ] }
logo = "white_halo.png"
