[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "RpVjixP8S1"
weight = 2

[[main]]
name = "About"
pageRef = "about"
identifier = "NlqCQ4b0q3"
weight = 1

[[footer]]
none = "none"
